on: [push]

jobs:
  scanforstring:
    runs-on: ubuntu-latest
    name: Scan for Copyright String
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan Step
      uses: actions/hello-world-docker-action@v1
      id: copyrightscan
      with:
        codefolders: './'
        fileextensions: '.md,.sh,.py'
        regex: '.*Copy.*'
        match: 0
        lines: 0
    # Use the output from the `hello` step
    - name: Get the output
      run: echo "${{ steps.copyrightscan.outputs.filelist }}"
